# Site settings
title: North Carpenter's Website
description: North Carpenters personal website
baseurl: "" # the subpath of your site, e.g., "/blog" if hosted in a subfolder
url: "https://NorthCarpenter.github.io" # your GitHub Pages URL

# Build settings
markdown: kramdown
theme: ""  # no theme
plugins: [] # empty for now, can add plugins later

# Optional: future defaults for pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: null