url: "northCarpenter.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "northCarpenter.github.io" # the subpath of your site, e.g. /blog
title: "North Carpenter's Personal Website" # the name of your site, e.g. ACME Corp.
description: "You found North's website. There are only 200 people named North (FN) in the US. Good job!" # a short description of your site